### ISSUE TITLE
Horrible and fragile code

### ISSUE THREAD

**Issue by andreiapostol** [AndreiCNitu/HPC#1]
^ see title

**Comment by AndreiCNitu** [comment]
🐀

**Comment by thewildnath** [comment]
@andreiapostol, if you find that entertainmenting, it just indicates that you have a most juvenile sense of the entellegence. It is pathetic that such childish activities can entertain one who's mind is so underdeveloped (unlike mine). I think you have much growing up to do, although I fear that even whenceupon you do so, you will still be just as immature and dumb as is the currency of the situation of your brian right now. It is the shame of the century, the darkness that glimmers as the light fades away into the snow. (Sorry, sometimes I let my axtensive creative writing skills bleed into my critisisms) My point being, develop your IQ so that you may find entertainment in more mature matters then this.
